### PR TITLE
Feature: Implemented orderType 'quote'

### PR DESCRIPTION
**Pull request by jekru**
It is required to send the parameter `quoteId` with the request ` POST https://www.wikifolio.com/api/virtualorder/placeorder` because otherwise the request fails as described in issue #10 .

To get quoteId, we first have to establish a websocket connection to: 

`wss://www.wikifolio.com/de/de/signalr/connect?transport=webSockets&clientProtocol=1.5&`**connectionToken={connectionToken}**`&connectionData=[{"name":"livehub"},{"name":"quotehub"}]&`**tid={tid}**

#### connectionToken

To get the connectionToken, we have to send a request to `GET https://www.wikifolio.com/de/de/signalr/negotiate?clientProtocol=1.5&connectionData=[{"name":"livehub"},{"name":"quotehub"}]&`**_={unix timestamp in ms}**

#### tid

The `tid` is calculated like this (see jquery.signalR-x.x.x.js):
```js
if (!ajaxPost) { url += "&tid=" + Math.floor(Math.random() * 11);
```

### Connect to the websocket

1. `wss://www.wikifolio.com/de/de/signalr/connect?transport=webSockets&clientProtocol=1.5&`**connectionToken={connectionToken}**`&connectionData=[{"name":"livehub"},{"name":"quotehub"}]&`**tid={tid}**

2. `GET https://www.wikifolio.com/de/de/signalr/start?transport=webSockets&clientProtocol=1.5&`**connectionToken={connectionToken}**`&connectionData=[{"name":"livehub"},{"name":"quotehub"}]&`**_={unix timestamp in ms}**

3. Connected!

### Get the quoteId

We have to send a message to the websocket:
```json
{
  "H":"quotehub",
  "M":"GetQuote",
  "A":["guid", "isin", "integer"],
  "I":1
}

```
A[0] := portfolio guid
A[1] := isin
A[2] := 910 | 920 (BUY | SELL)
I := incrementing integer (looks that the value of this parameter is not that important)

The response of this message will be an object that contains the `quoteId`. Now we can add this parameter to the request in the function `submit()`.

### CODE REVIEW

**Comment by RienNeVaPlus** [comment]
Great work, thank you jekru

**Comment by henrydatei** [comment]
I'm working on a similar project in Python (https://github.com/henrydatei/wikifolio-api) and I'm trying to implement the quote order with @stubi95. We both have a problem with the `tid` parameter. As you mentioned its a random number between 0 and 10, so in python I have tried 
```python
tid = random.randint(0,10)
```
but then the WebSocket connection is only in around 1 in 10 tries successful. Setting the value of `tid` to 1 or even removing the parameter from the requests leads to same problem. I assume that the WebSocket server also calculates some sort of random number and this has to match with the `tid` (but this sounds really stupid!). Do you have this problem with only every 10th connection is successful?

**Comment by jekru** [comment]
@henrydatei 

I am not sure if the `tid` parameter is even necessary. With "setting the value of `tid` to 1 or even removing the parameter from thje requests leads to the same problem", you mean that the connection still works every 10th request? That would mean that the problem is not caused by the `tid` parameter but maybe with your websocket implementation. Did you try other websocket endpoints (not wikifolio) to be sure that the implementation is valid?

What about **unix timestamp in ms**? At what point do you calculate this? After this is calculated, you should send the request immediately and not perform any tasks that take a long time because the backend is probably checking if the timestamp lies in a range with the server time. My guess is that the problem lies here because if every 10th request is successful, this sounds like a time problem.

**Comment by henrydatei** [comment]
> With "setting the value of tid to 1 or even removing the parameter from the requests leads to the same problem", you mean that the connection still works every 10th request?

Yes

> Did you try other websocket endpoints (not wikifolio) to be sure that the implementation is valid?

Yes, I use https://github.com/websocket-client/websocket-client and the example worked perfectly

> What about unix timestamp in ms?

I haven't implemented this at all and I'm not sending this parameter. Maybe here is the problem... I'll implement this and see if its working

**Comment by henrydatei** [comment]
Update: I've implemented the timestamp in ms but the problem with only every 10th request working is still there.

**Comment by jekru** [comment]
> Update: I've implemented the timestamp in ms but the problem with only every 10th request working is still there.

What is the result if the request is working? Are you sure that the connection works correct and that you receive data?

**Comment by henrydatei** [comment]
This is what I get when everything is working:
```
(1, b'{"C":"d-91682F4F-B1,0|QJ6,0|B3,0|QJ7,1|QJ8,1","M":[{"H":"QuoteHub","M":"quoteCallback","A":[{"QuoteId":"70021b6e-bfd2-4321-bad0-04f0b9dbbfa4","WaitForManuelResponse":false,"Ask":6.2,"Bid":5.65,"ValidityDuration":3000,"Currency":"EUR"}]}]}')
```
with the quoteID I can execute the order:
```
{'success': True, 'reason': '', 'orderGuid': '8df8a1d0-ea89-47c5-8c41-bb8fff6da484'}
```

If it's not working I get this:
```
Traceback (most recent call last):
  File "/home/henry/Downloads/GitHub/wikifolio-api/text.py", line 7, in <module>
    wf.buy_quote()
  File "/home/henry/Downloads/GitHub/wikifolio-api/wikifolio.py", line 329, in buy_quote
    ws.connect(socket)
  File "/home/henry/.local/lib/python3.8/site-packages/websocket/_core.py", line 250, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/home/henry/.local/lib/python3.8/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/henry/.local/lib/python3.8/site-packages/websocket/_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
```

**Comment by jekru** [comment]
The result of you successful request is indeed valid. Could you print the data you are using for an unsuccesful request? For example url, headers, etc.

Please don't share personal data like your cookies!

**Comment by henrydatei** [comment]
It is literally the same code that has different behavior. I've pushed everything to https://github.com/henrydatei/wikifolio-api and when you execute
```python
from wikifolio import Wikifolio

wf = Wikifolio("email", "password", "name of wikifolio e.g. wf000igb03")
wf.buy_quote(1, "GB0001638955")
```
I got the error.

**Comment by jekru** [comment]
The same code doesn't necessary mean same variable values, that's why I ask.

**Comment by henrydatei** [comment]
I know. The only thing that changed is the connection token and the login cookie. A connection token for a failed request is `V7uK3sK52JMQ1rDZwj6XJM4Z8xiQ2+MXvrd+kSV1XqUDMvkt8PML8xoVd9ywVnBb9U9ukOLtQJOVu5+0m+5+nkJmpX92xg4HeNJJhcMibFk9Blce`

**Pull request merged**
